# Build stage
FROM node:20 AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN npx ng build --configuration production

# Runtime stage
FROM nginx:alpine
# Remove default nginx welcome page
RUN rm -rf /usr/share/nginx/html/*
# Copy built assets
COPY --from=build /app/dist/browser /usr/share/nginx/html
# Copy custom Nginx config
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]